In [2]:
import pandas as pd 
import seaborn as sns
import matplotlib as plt

sns.set(style="whitegrid", palette="muted")

In [3]:
df=pd.read_csv('data/aminoacids.csv')

In [4]:
df

,Name,Abbr,Letter,Molecular Weight,Molecular Formula,Residue Formula,Residue Weight,pKa1,pKb2,pKx3,...,VSC,P1,P2,SASA,NCISC,carbon,hydrogen,nitrogen,oxygen,sulfur
0,Alanine,Ala,A,89.10,C3H7NO2,C3H5NO,71.08,2.34,9.69,NaN,...,27.5,8.1,0.046,1.181,0.007187,3,7,1,2,0
1,Cysteine,Cys,C,121.16,C3H7NO2S,C3H5NOS,103.15,1.96,10.28,8.18,...,44.6,5.5,0.128,1.461,-0.036610,3,7,1,2,1
2,Aspartic acid,Asp,D,133.11,C4H7NO4,C4H5NO3,115.09,1.88,9.60,3.65,...,40.0,13.0,0.105,1.587,-0.023820,4,7,1,4,0
3,Glutamic acid,Glu,E,147.13,C5H9NO4,C5H7NO3,129.12,2.19,9.67,4.25,...,62.0,12.3,0.151,1.862,0.006802,5,9,1,4,0
4,Phenylalanine,Phe,F,165.19,C9H11NO2,C9H9NO,147.18,1.83,9.13,NaN,...,115.5,5.2,0.290,2.228,0.037552,9,11,1,2,0
5,Glycine,Gly,G,75.07,C2H5NO2,C2H3NO,57.05,2.34,9.60,NaN,...,0.0,9.0,0.000,0.881,0.179052,2,5,1,2,0
6,Histidine,His,H,155.16,C6H9N3O2,C6H7N3O,137.14,1.82,9.17,6.00,...,79.0,10.4,0.230,2.025,-0.010690,6,9,3,2,0
7,Isoleucine,Ile,I,131.18,C6H13NO2,C6H11NO,113.16,2.36,9.60,NaN,...,93.5,5.2,0.186,1.810,0.021631,6,13,1,2,0
8,Lysine,Lys,K,146.19,C6H14N2O2,C6H12N2O,128.18,2.18,8.95,10.53,...,100.0,11.3,0.219,2.258,0.017708,6,14,2,2,0
9,Leucine,Leu,L,131.18,C6H13NO2,C6H11NO,113.16,2.36,9.60,NaN,...,93.5,4.9,0.186,1.931,0.051672,6,13,1,2,0
10,Methionine,Met,M,149.21,C5H11NO2S,C5H9NOS,131.20,2.28,9.21,NaN,...,94.1,5.7,0.221,2.034,0.002683,5,11,1,2,1
11,Asparagine,Asn,N,132.12,C4H8N2O3,C4H6N2O2,114.11,2.02,8.80,NaN,...,58.7,11.6,0.134,1.655,0.005392,4,8,2,3,0
12,Hydroxyproline,Hyp,O,131.13,C5H9NO3,C5H7NO2,113.11,1.82,9.65,NaN,...,NaN,NaN,NaN,NaN,NaN,5,9,1,3,0
13,Proline,Pro,P,115.13,C5H9NO2,C5H7NO,97.12,1.99,10.60,NaN,...,41.9,8.0,0.131,1.468,0.239531,5,9,1,2,0
14,Glutamine,Gln,Q,146.15,C5H10N2O3,C5H8N2O2,128.13,2.17,9.13,NaN,...,80.7,10.5,0.180,1.932,0.049211,5,10,2,3,0
15,Arginine,Arg,R,174.20,C6H14N4O2,C6H12N4O,156.19,2.17,9.04,12.48,...,105.0,10.5,0.291,2.560,0.043587,6,14,4,2,0
16,Serine,Ser,S,105.09,C3H7NO3,C3H5NO2,87.08,2.21,9.15,NaN,...,29.3,9.2,0.062,1.298,0.004627,3,7,1,3,0
17,Threonine,Thr,T,119.12,C4H9NO3,C4H7NO2,101.11,2.09,9.10,NaN,...,51.3,8.6,0.108,1.525,0.003352,4,9,1,3,0
18,Pyroglutamatic,Glp,U,139.11,C5H7NO3,C5H5NO2,121.09,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5,7,1,3,0
19,Valine,Val,V,117.15,C5H11NO2,C5H9NO,99.13,2.32,9.62,NaN,...,71.5,5.9,0.140,1.645,0.057004,5,11,1,2,0
20,Tryptophan,Trp,W,204.23,C11H12N2O2,C11H10N2O,186.22,2.83,9.39,NaN,...,145.5,5.4,0.409,2.663,0.037977,11,12,2,2,0
21,Tyrosine,Tyr,Y,181.19,C9H11NO3,C9H9NO2,163.18,2.20,9.11,10.07,...,117.3,6.2,0.298,2.368,0.023599,9,11,1,3,0

In [5]:
df.shape

(22, 22)

In [6]:
df.columns

Index(['Name', 'Abbr', 'Letter', 'Molecular Weight', 'Molecular Formula',
       'Residue Formula', 'Residue Weight', 'pKa1', 'pKb2', 'pKx3', 'pl4', 'H',
       'VSC', 'P1', 'P2', 'SASA', 'NCISC', 'carbon', 'hydrogen', 'nitrogen',
       'oxygen', 'sulfur'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               22 non-null     object
 1   Abbr               22 non-null     object
 2   Letter             22 non-null     object
 3   Molecular Weight   22 non-null     float64
 4   Molecular Formula  22 non-null     object
 5   Residue Formula    22 non-null     object
 6   Residue Weight     22 non-null     float64
 7   pKa1               21 non-null     float64
 8   pKb2               21 non-null     float64
 9   pKx3               7 non-null      float64
 10  pl4                21 non-null     float64
 11  H                  20 non-null     float64
 12  VSC                20 non-null     float64
 13  P1                 20 non-null     float64
 14  P2                 20 non-null     float64
 15  SASA               20 non-null     float64
 16  NCISC              20 non-null     float64
 17  carbon             22 non-null     int64
 18  hydrogen           22 non-null     int64
 19  nitrogen           22 non-null     int64
 20  oxygen             22 non-null     int64
 21  sulfur             22 non-null     int64
dtypes: float64(12), int64(5), object(5)
memory usage: 3.9+ KB

In [8]:
df.describe(include='all')

,Name,Abbr,Letter,Molecular Weight,Molecular Formula,Residue Formula,Residue Weight,pKa1,pKb2,pKx3,...,VSC,P1,P2,SASA,NCISC,carbon,hydrogen,nitrogen,oxygen,sulfur
count,22,22,22,22.000000,22,22,22.000000,21.000000,21.000000,7.000000,...,20.000000,20.000000,20.000000,20.000000,20.000000,22.000000,22.000000,22.000000,22.000000,22.000000
unique,22,22,22,NaN,21,21,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Alanine,Ala,A,NaN,C6H13NO2,C6H11NO,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,1,1,NaN,2,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,136.740909,NaN,NaN,118.726364,2.160000,9.432857,7.880000,...,72.545000,8.325000,0.175750,1.818600,0.035872,5.318182,9.681818,1.409091,2.500000,0.090909
std,NaN,NaN,NaN,29.387263,NaN,NaN,29.389193,0.239917,0.434927,3.358392,...,36.364521,2.690505,0.097589,0.461453,0.065018,2.124379,2.533328,0.796366,0.672593,0.294245
min,NaN,NaN,NaN,75.070000,NaN,NaN,57.050000,1.820000,8.800000,3.650000,...,0.000000,4.900000,0.000000,0.881000,-0.036610,2.000000,5.000000,1.000000,2.000000,0.000000
25%,NaN,NaN,NaN,119.630000,NaN,NaN,101.620000,1.990000,9.130000,5.125000,...,43.925000,5.650000,0.123000,1.510750,0.004308,4.000000,7.250000,1.000000,2.000000,0.000000
50%,NaN,NaN,NaN,132.615000,NaN,NaN,114.600000,2.180000,9.390000,8.180000,...,75.250000,8.350000,0.165500,1.836000,0.019669,5.000000,9.000000,1.000000,2.000000,0.000000
75%,NaN,NaN,NaN,148.690000,NaN,NaN,130.680000,2.320000,9.620000,10.300000,...,95.575000,10.500000,0.223250,2.082500,0.044993,6.000000,11.000000,1.750000,3.000000,0.000000
max,NaN,NaN,NaN,204.230000,NaN,NaN,186.220000,2.830000,10.600000,12.480000,...,145.500000,13.000000,0.409000,2.663000,0.239531,11.000000,14.000000,4.000000,4.000000,1.000000

In [9]:
# Checking for missing values
missing_values= df.isnull().sum()

In [10]:
missing_values

Name                  0
Abbr                  0
Letter                0
Molecular Weight      0
Molecular Formula     0
Residue Formula       0
Residue Weight        0
pKa1                  1
pKb2                  1
pKx3                 15
pl4                   1
H                     2
VSC                   2
P1                    2
P2                    2
SASA                  2
NCISC                 2
carbon                0
hydrogen              0
nitrogen              0
oxygen                0
sulfur                0
dtype: int64

In [12]:
# Check for duplicates
duplicates= df.duplicated().sum()
duplicates

np.int64(0)